### PR TITLE
Fix Validation Issues (#10)

### PR DESCRIPTION
**Pull request by mr-martian**

### CODE REVIEW

**Comment by ftyers** [comment]
Thanks @mr-martian ! @dan-zeman can you check this out?

**Comment by dan-zeman** [comment]
I suspect that the `nsubj:outer` on line 2031 is wrong.

_Tað eru 10 býir í Oskarshamns kommunu._

With the help of Google Icelandic (:-)) translator, I understand it as "There are 10 villages in Oskarshamn municipality." It does not sound like the typical construction for which `nsubj:outer` was designed. And the previous sentence

_Tað eru átta býir og bygdir í Hultsfreds kommunu._

is very similar and does not need `nsubj:outer`; it uses `expl` instead.

Finally, as we are already looking at these sentences, I believe that the preposition _í_ should be attached to _kommunu_, not to the genitive `PROPN` that modifies it.

**Comment by dan-zeman** [comment]
I went ahead and fixed the file (08beffd4781caea1bf95b97e5fa133d0271f235c) along the lines of my previous post. I need the file to be at least back to LEGACY status, i.e., no new unknown deprel errors.

**Comment by mr-martian** [comment]
On the `nsubj`/`expl` I was going solely based on the trees and for the preposition attachment I just went too quickly and missed the second noun.

**Pull request merged**
